use_frameworks!

target 'ChainableSwift_Example', :exclusive => true do
  pod 'ChainableSwift', :path => '../'

  pod 'PureLayout'
end

target 'ChainableSwift_Tests', :exclusive => true do
  pod 'ChainableSwift', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
