use_frameworks!
platform :ios, '8.0'

target 'ChainableSwift_Example' do
  inherit! :search_paths
  pod 'ChainableSwift', :path => '../'

  pod 'PureLayout'
end

target 'ChainableSwift_Tests' do
  inherit! :search_paths
  pod 'ChainableSwift', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
